name: deploy-backend

on:
  push:
    branches:
      - main

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2 and restart PM2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~
            rm -rf muawin
            git clone https://github.com/CheezyApp/Muawin.git muawin
            cd muawin/backend

            npm install

            pm2 restart index.js || pm2 start index.js
